// =============================================================================
// WPF APPLICATION ENTRY POINT
// =============================================================================
//
// C# / WPF CONCEPT: The Application Class
// ========================================
//
// Every WPF application has an App class that inherits from Application.
// This class:
// - Is the entry point (like main() in console apps)
// - Manages application lifecycle (startup, shutdown)
// - Hosts application-wide resources (styles, themes)
// - Handles unhandled exceptions
//
// HOW WPF STARTUP WORKS:
// ---------------------
//
//   1. Program starts
//         |
//         v
//   2. App.xaml is processed
//      - Loads resources
//      - Sets StartupUri="MainWindow.xaml"
//         |
//         v
//   3. MainWindow is created and shown
//         |
//         v
//   4. Event loop runs until window closes
//
// WHERE IS MAIN()?
// ----------------
// Unlike console apps, WPF apps hide the Main() method.
// It's auto-generated by the build system from App.xaml.
// The generated code looks roughly like:
//
//   public static void Main()
//   {
//       var app = new App();
//       app.InitializeComponent();
//       app.Run();
//   }
//
// =============================================================================
// C# CONCEPTS IN THIS FILE
// =============================================================================
//
// 1. PARTIAL CLASS
//    `public partial class App`
//    The class is split across multiple files:
//    - App.xaml.cs (this file) - Code-behind with C# logic
//    - App.xaml - XAML markup for resources and configuration
//    The compiler merges them into one class.
//
// 2. INHERITANCE FROM WPF BASE CLASS
//    `App : Application`
//    The Application class provides window management, resource lookup,
//    and the main message loop.
//
// 3. EMPTY CLASS BODY
//    This class has no additional code because:
//    - App.xaml defines StartupUri (which window to show)
//    - App.xaml can define resources, styles, themes
//    - For simple apps, no custom startup logic is needed
//
//    For more complex apps, you might override:
//    - OnStartup() - Custom initialization
//    - OnExit() - Cleanup before shutdown
//    - OnActivated() / OnDeactivated() - App focus changes
//
// =============================================================================

using System.Windows;

namespace AerospaceDashboard;

/// <summary>
/// Application entry point and lifecycle manager.
/// </summary>
/// <remarks>
/// <para>
/// C# CONCEPT: Partial Class
/// This class is "partial" - it's split between App.xaml.cs (this file)
/// and App.xaml. The compiler merges them at build time.
///
/// The XAML file (App.xaml) contains:
/// - StartupUri: Which window to show first
/// - Application.Resources: Styles and themes
/// </para>
/// <para>
/// WPF LIFECYCLE:
/// The Application class runs the Windows message loop and manages
/// windows. When the last window closes (or Shutdown() is called),
/// the application exits.
/// </para>
/// </remarks>
public partial class App : Application
{
    // =========================================================================
    // This class is intentionally empty for simple applications.
    // =========================================================================
    //
    // The XAML file (App.xaml) handles configuration:
    //   <Application StartupUri="MainWindow.xaml" ... />
    //
    // For more complex apps, you might add:
    //
    // protected override void OnStartup(StartupEventArgs e)
    // {
    //     base.OnStartup(e);
    //     // Custom initialization: logging, DI container, config loading
    // }
    //
    // protected override void OnExit(ExitEventArgs e)
    // {
    //     base.OnExit(e);
    //     // Cleanup: save settings, close connections
    // }
}
